GET http://localhost:3000/api/blogs

###

GET http://localhost:3000/blogs/

###

POST http://localhost:5000/blogs
Content-Type: application/json

{
    "topic" : "Blog Six Topic",  
    "genre" : "a nice genre" ,   
    "fullText" : "a full text from post request",
    "image" : "imagelink001"    
}

###
Delete http://localhost:5000/blogs/6
